version: '3'

services:
  postgis:
    hostname: postgis
    container_name: postgis
    image: kartoza/postgis:11.0-2.5
    restart: on-failure
    env_file:
      - ./env/postgis.env
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
    ports:
      - 15432:5432
    networks:
      - pgadmin4-network

  pgadmin4:
    hostname: pgadmin4
    container_name: pgadmin4
    image: dpage/pgadmin4:4.15
    restart: on-failure
    env_file:
      - ./env/pgadmin4.env
    volumes:
      - ./volumes/pgadmin4:/var/lib/pgadmin
    # ports:
    #   - 15430:80
    depends_on:
      - postgis
    # networks:
    #   - pgadmin4-network
    # http://localhost:15430/ (pgadmin4-network network)
    network_mode: host
    # http://localhost/ (host network)

networks:
  pgadmin4-network:
    driver: bridge
